### PR TITLE
frontend: add school-header in vote-print

### PR DESCRIPTION
**Pull request by Lordnoname**
Todo: Add users form to print-out

### CODE REVIEW

**Comment by gilgda** [comment]
I´m in for it just need to consider one question: 
Didn´t we want to have two separate evaluation sheets?
(One for the student which has to be signed and the other one with ALL results on ONE sheet)

**Comment by gilgda** [comment]
Removed the old printTemplate and added two new ones :

- result template: shows the results of the whole vote and is considered to be displayed at the OSK office

- user template: shows the voting of one student and is considered to be signed and handed back in to the OSK

**Comment by gilgda** [comment]
This PR still needs some work:

1. integrating the templates into the frontend components

2.  numbering the voteable seminars in the user template

**Comment by gilgda** [comment]
The result template is now added to the component but is not working properly by now.
Fix is on the way 👍

**Comment by gilgda** [comment]
Templates are almost fully built but there is a problem displaying the evaluation printout as it just displays the user template when clicking on "Drucken" in "Auswertung" (build the program on your own to see the problem).
Need help fixing that please.

**Comment by Lordnoname** [comment]
@gilgda fixed your issue in a commit. Please look at the results and improve it again :)

**Comment by gilgda** [comment]
IMO the conflicts should be resolved by editing the existing voting-details-admin component on the master.

**Comment by Lordnoname** [comment]
I will fix those conflicts for you tomorrow :)

**Comment by Lordnoname** [comment]
@gilgda why merging this unfinished pr?
[seminarwahl.pdf](https://github.com/Werdenfels-Gymnasium/voting-calculator/files/1539211/seminarwahl.pdf)

**Pull request merged**
